spring:
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  mustache:
    cache: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true